#pragma once
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <winrt/Windows.Foundation.h>
#include <memory>
#include <string>
#include <functional>
#include <thread>
#include <chrono>
