name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28'
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: |
        nuget restore build/src/WindowLib/WindowLib.vcxproj -PackagesDirectory packages
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
    
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WindowLib-${{env.BUILD_TYPE}}
        path: |
          build/src/WindowLib/${{env.BUILD_TYPE}}/WindowLib.dll
          build/src/WindowLib/${{env.BUILD_TYPE}}/WindowLib.lib
          build/src/TestApp/${{env.BUILD_TYPE}}/TestApp.exe
          build/src/TestApp/${{env.BUILD_TYPE}}/TestApp.pdb
